export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const SIMILAR_RECIPES_REQUEST = 'SIMILAR_RECIPES_REQUEST';
export const SIMILAR_RECIPES_SUCCESS = 'SIMILAR_RECIPES_SUCCESS';
export const SIMILAR_RECIPES_FAIL = 'SIMILAR_RECIPES_FAIL';
